version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
      production-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
    ignore:
      # @types/node は Node.js のバージョンに合わせて手動で更新するため対象外にする
      - dependency-name: "@types/node"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
